### PR TITLE
Remove transform that causes drag lag

### PR DESCRIPTION
**Pull request by developit**
See the before & after here:

preview

### CODE REVIEW

**Comment by xtuc** [comment]
Yeah I noticed that too, that looks good! Thanks

**Comment by SaraVieira** [comment]
Thank you so much @developit ! Merged and deployed ! 🎉

**Comment by developit** [comment]
related: how awesome is the phrase "drag lag"

**Comment by xtuc** [comment]
Personally it's more drague lag.

**Pull request merged**
